### ISSUE TITLE
loot don't work

### ISSUE THREAD

**Issue by 44wrw44** [Rosewood-Development/RoseLoot#19]
[16:51:36 INFO]: 44_wrw_44 issued server command: /loot giveitems shulker_loot
[16:51:36 WARN]: java.lang.reflect.InvocationTargetException
[16:51:36 WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
[16:51:36 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.lib.rosegarden.command.framework.RoseCommandWrapper.executeCommand(RoseCommandWrapper.java:293)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.lib.rosegarden.command.framework.RoseCommandWrapper.runCommand(RoseCommandWrapper.java:282)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.lib.rosegarden.command.framework.RoseCommandWrapper.execute(RoseCommandWrapper.java:221)
[16:51:36 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[16:51:36 WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:982)
[16:51:36 WARN]: at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[16:51:36 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[16:51:36 WARN]: at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[16:51:36 WARN]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[16:51:36 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2379)
[16:51:36 WARN]: at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2339)
[16:51:36 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[16:51:36 WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:51:36 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:51:36 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:51:36 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[16:51:36 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1345)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338)
[16:51:36 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1316)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204)
[16:51:36 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[16:51:36 WARN]: at java.base/java.lang.Thread.run(Thread.java:1589)
[16:51:36 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "dev.rosewood.roseloot.provider.NumberProvider.getInteger(dev.rosewood.roseloot.loot.context.LootContext)" because "this.amount" is null
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.loot.item.ItemLootItem.getAllItems(ItemLootItem.java:121)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.loot.LootEntry.getAllItems(LootEntry.java:88)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.loot.LootPool.lambda$getAllItems$1(LootPool.java:60)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
[16:51:36 WARN]: at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.loot.LootPool.getAllItems(LootPool.java:60)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.loot.LootTable.lambda$getAllItems$1(LootTable.java:46)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
[16:51:36 WARN]: at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
[16:51:36 WARN]: at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
[16:51:36 WARN]: at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.loot.LootTable.getAllItems(LootTable.java:46)
[16:51:36 WARN]: at RoseLoot-1.1.17.jar//dev.rosewood.roseloot.command.command.GiveItemsCommand.execute(GiveItemsCommand.java:42)
[16:51:36 WARN]: at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[16:51:36 WARN]: ... 27 more

**Comment by Esophose** [comment]
Can you please join our support Discord server and verify that you've purchased the plugin to receive support? Thanks. https://discord.gg/MgUsTBK
